version: '3.8'

services:
  springboot-app:
    build: .
    image: paypal-spring-boot-app
    container_name: paypal-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./logs:/logs
